# Site settings
title: Blog
header-img: img/home-bg1.jpg
email: 944296934@qq.com
copyright_name: soulmate803
description: "顿顿的个人博客"
baseurl: "https://soulmate803.github.io/soulmate-blog"
url: "/soulmate-blog"
github_username:  soulmate803
email_username:  944296934@qq.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 2
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
