# Site settings
title: Blog
header-img: img/home-bg1.jpg
email: 944296934@qq.com
copyright_name: soulmate803
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: "/soulmate803.github.io"
url: "https://soulmate803.github.io"
twitter_username: soulmate803
github_username:  soulmate803
facebook_username:  soulmate803
email_username:  944296934@qq.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
